"""Tests for the BibTeX exporter."""

import json
from pathlib import Path

import pytest

from academic_research_toolkit.exporters.bibtex import BibTeXExporter


@pytest.fixture
def exporter():
    """Create a BibTeXExporter instance."""
    return BibTeXExporter()


@pytest.fixture
def sample_book_citation():
    """Sample book citation."""
    return {
        "citation_type": "book",
        "authors": ["Smith, John", "Doe, Jane"],
        "title": "Introduction to Artificial Intelligence",
        "year": "2020",
        "publisher": "Academic Press",
        "location": "New York",
    }


@pytest.fixture
def sample_article_citation():
    """Sample journal article citation."""
    return {
        "citation_type": "article",
        "authors": ["Johnson, Robert"],
        "title": "Machine Learning Applications in Healthcare",
        "year": "2021",
        "source": "Journal of AI Research",
        "volume": "15",
        "issue": "3",
        "pages": "100-120",
        "doi": "10.1234/jair.2021.001",
    }


@pytest.fixture
def sample_citations(sample_book_citation, sample_article_citation):
    """List of sample citations."""
    return [sample_book_citation, sample_article_citation]


class TestBibTeXExporter:
    """Tests for BibTeXExporter class."""

    def test_export_book_citation(self, exporter, sample_book_citation):
        """Test exporting a single book citation."""
        result = exporter.export([sample_book_citation])

        assert "@book{" in result
        assert "author = {Smith, John and Doe, Jane}" in result
        assert "title = {Introduction to Artificial Intelligence}" in result
        assert "year = {2020}" in result
        assert "publisher = {Academic Press}" in result
        assert "address = {New York}" in result

    def test_export_article_citation(self, exporter, sample_article_citation):
        """Test exporting a journal article citation."""
        result = exporter.export([sample_article_citation])

        assert "@article{" in result
        assert "author = {Johnson, Robert}" in result
        assert "title = {Machine Learning Applications in Healthcare}" in result
        assert "year = {2021}" in result
        assert "journal = {Journal of AI Research}" in result
        assert "volume = {15}" in result
        assert "number = {3}" in result
        assert "pages = {100-120}" in result
        assert "doi = {10.1234/jair.2021.001}" in result

    def test_export_multiple_citations(self, exporter, sample_citations):
        """Test exporting multiple citations."""
        result = exporter.export(sample_citations)

        assert "@book{" in result
        assert "@article{" in result
        # Both entries should be separated by newlines
        assert result.count("@") == 2

    def test_generate_unique_keys(self, exporter):
        """Test that duplicate citations get unique keys."""
        citations = [
            {
                "authors": ["Smith, John"],
                "title": "Test Book",
                "year": "2020",
            },
            {
                "authors": ["Smith, John"],
                "title": "Test Book",
                "year": "2020",
            },
        ]
        result = exporter.export(citations)

        # Should have two different keys
        assert "smith_2020_test," in result
        assert "smith_2020_test_1," in result

    def test_latex_escaping(self, exporter):
        """Test that special LaTeX characters are escaped."""
        citation = {
            "authors": ["O'Brien, Patrick & Sons"],
            "title": "Testing & Special $Characters# in Titles",
            "year": "2020",
        }
        result = exporter.export([citation])

        assert r"\&" in result
        assert r"\$" in result
        assert r"\#" in result

    def test_unicode_handling(self, exporter):
        """Test that Unicode characters are converted to LaTeX."""
        citation = {
            "authors": ["Müller, Hans", "García, José"],
            "title": "Café Culture",
            "year": "2020",
        }
        result = exporter.export([citation])

        # Unicode should be converted to LaTeX commands
        assert r"\"u" in result or "Müller" in result  # Either escaped or raw

    def test_save_to_file(self, exporter, sample_citations, tmp_path):
        """Test saving citations to a .bib file."""
        output_path = tmp_path / "test.bib"
        result = exporter.save(sample_citations, output_path)

        assert Path(result).exists()
        content = Path(result).read_text()
        assert "% BibTeX file generated by Academic Research Toolkit" in content
        assert "@book{" in content
        assert "@article{" in content

    def test_load_citations_from_list(self, exporter, tmp_path):
        """Test loading citations from a JSON file with list format."""
        citations = [
            {"authors": ["Smith"], "title": "Test", "year": "2020"},
        ]
        json_path = tmp_path / "citations.json"
        json_path.write_text(json.dumps(citations))

        loaded = exporter.load_citations(json_path)
        assert len(loaded) == 1
        assert loaded[0]["title"] == "Test"

    def test_load_citations_from_dict(self, exporter, tmp_path):
        """Test loading citations from a JSON file with dict format."""
        data = {
            "citations": [
                {"authors": ["Smith"], "title": "Test", "year": "2020"},
            ]
        }
        json_path = tmp_path / "citations.json"
        json_path.write_text(json.dumps(data))

        loaded = exporter.load_citations(json_path)
        assert len(loaded) == 1
        assert loaded[0]["title"] == "Test"

    def test_empty_citations(self, exporter):
        """Test exporting empty citation list."""
        result = exporter.export([])
        assert result == ""

    def test_minimal_citation(self, exporter):
        """Test exporting a citation with minimal fields."""
        citation = {"title": "Just a Title"}
        result = exporter.export([citation])

        assert "@misc{" in result
        assert "title = {Just a Title}" in result

    def test_citation_key_sanitization(self, exporter):
        """Test that citation keys are properly sanitized."""
        citation = {
            "authors": ["Müller-Schmidt, Hans"],
            "title": "Test: A Study?",
            "year": "2020",
        }
        result = exporter.export([citation])

        # Key should be ASCII and URL-safe
        lines = result.split("\n")
        key_line = [l for l in lines if l.startswith("@")][0]
        key = key_line.split("{")[1].rstrip(",")
        assert all(c.isalnum() or c == "_" for c in key)

    def test_unclassified_citation_type(self, exporter):
        """Test that unclassified citations become misc entries."""
        citation = {
            "citation_type": "unclassified",
            "authors": ["Smith"],
            "title": "Unknown Type",
            "year": "2020",
        }
        result = exporter.export([citation])
        assert "@misc{" in result

    def test_url_field(self, exporter):
        """Test that URL field is included."""
        citation = {
            "authors": ["Smith"],
            "title": "Online Resource",
            "year": "2020",
            "url": "https://example.com/resource",
        }
        result = exporter.export([citation])
        assert "url = {https://example.com/resource}" in result

    def test_notes_field(self, exporter):
        """Test that notes field is included."""
        citation = {
            "authors": ["Smith"],
            "title": "Test",
            "year": "2020",
            "notes": "This is a special note",
        }
        result = exporter.export([citation])
        assert "note = {This is a special note}" in result


class TestBibTeXExporterHelpers:
    """Tests for BibTeXExporter helper methods."""

    def test_extract_last_name_comma_format(self, exporter):
        """Test extracting last name from 'Last, First' format."""
        assert exporter._extract_last_name("Smith, John") == "Smith"

    def test_extract_last_name_space_format(self, exporter):
        """Test extracting last name from 'First Last' format."""
        assert exporter._extract_last_name("John Smith") == "Smith"

    def test_extract_last_name_single(self, exporter):
        """Test extracting last name from single word."""
        assert exporter._extract_last_name("Aristotle") == "Aristotle"

    def test_extract_last_name_empty(self, exporter):
        """Test extracting last name from empty string."""
        assert exporter._extract_last_name("") == "unknown"

    def test_get_title_word_basic(self, exporter):
        """Test getting first significant word from title."""
        assert exporter._get_title_word("Introduction to AI") == "introduction"

    def test_get_title_word_skips_articles(self, exporter):
        """Test that articles are skipped."""
        assert exporter._get_title_word("The Art of Programming") == "art"
        assert exporter._get_title_word("A Brief History") == "brief"
        assert exporter._get_title_word("An Introduction") == "introduction"

    def test_sanitize_key_special_chars(self, exporter):
        """Test sanitizing key with special characters."""
        assert exporter._sanitize_key("smith-2020-test!") == "smith_2020_test"

    def test_sanitize_key_unicode(self, exporter):
        """Test sanitizing key with Unicode."""
        result = exporter._sanitize_key("müller_2020")
        assert all(c.isascii() for c in result)
