"""BibTeX exporter for citations."""

import json
import re
import unicodedata
from pathlib import Path
from typing import Dict, List, Optional


class BibTeXExporter:
    """Export citations to BibTeX format."""

    # LaTeX special character mappings
    LATEX_ESCAPES = {
        "&": r"\&",
        "%": r"\%",
        "$": r"\$",
        "#": r"\#",
        "_": r"\_",
        "{": r"\{",
        "}": r"\}",
        "~": r"\textasciitilde{}",
        "^": r"\textasciicircum{}",
    }

    # Unicode to LaTeX accent mappings
    UNICODE_TO_LATEX = {
        "á": r"\'a",
        "à": r"\`a",
        "ä": r"\"a",
        "â": r"\^a",
        "ã": r"\~a",
        "å": r"\aa{}",
        "æ": r"\ae{}",
        "ç": r"\c{c}",
        "é": r"\'e",
        "è": r"\`e",
        "ë": r"\"e",
        "ê": r"\^e",
        "í": r"\'i",
        "ì": r"\`i",
        "ï": r"\"i",
        "î": r"\^i",
        "ñ": r"\~n",
        "ó": r"\'o",
        "ò": r"\`o",
        "ö": r"\"o",
        "ô": r"\^o",
        "õ": r"\~o",
        "ø": r"\o{}",
        "ú": r"\'u",
        "ù": r"\`u",
        "ü": r"\"u",
        "û": r"\^u",
        "ý": r"\'y",
        "ÿ": r"\"y",
        "ß": r"\ss{}",
        "Á": r"\'A",
        "À": r"\`A",
        "Ä": r"\"A",
        "Â": r"\^A",
        "Ã": r"\~A",
        "Å": r"\AA{}",
        "Æ": r"\AE{}",
        "Ç": r"\c{C}",
        "É": r"\'E",
        "È": r"\`E",
        "Ë": r"\"E",
        "Ê": r"\^E",
        "Í": r"\'I",
        "Ì": r"\`I",
        "Ï": r"\"I",
        "Î": r"\^I",
        "Ñ": r"\~N",
        "Ó": r"\'O",
        "Ò": r"\`O",
        "Ö": r"\"O",
        "Ô": r"\^O",
        "Õ": r"\~O",
        "Ø": r"\O{}",
        "Ú": r"\'U",
        "Ù": r"\`U",
        "Ü": r"\"U",
        "Û": r"\^U",
        "Ý": r"\'Y",
        "Ÿ": r"\"Y",
    }

    # Map citation types to BibTeX entry types
    TYPE_MAP = {
        "book": "book",
        "article": "article",
        "journal": "article",
        "interview": "misc",
        "online": "misc",
        "archival": "misc",
        "unclassified": "misc",
    }

    def __init__(self):
        """Initialize the BibTeX exporter."""
        self._used_keys = set()

    def export(self, citations: List[Dict]) -> str:
        """
        Convert citations to BibTeX entries.

        Args:
            citations: List of citation dictionaries with fields like
                       authors, year, title, publisher, etc.

        Returns:
            BibTeX formatted string with all entries.
        """
        self._used_keys = set()
        entries = []

        for citation in citations:
            entry = self._format_entry(citation)
            if entry:
                entries.append(entry)

        return "\n\n".join(entries)

    def save(self, citations: List[Dict], output_path: Path) -> str:
        """
        Save citations to .bib file.

        Args:
            citations: List of citation dictionaries.
            output_path: Path to output .bib file.

        Returns:
            Path to the saved file as string.
        """
        output_path = Path(output_path)
        bibtex_content = self.export(citations)

        # Add header comment
        header = (
            "% BibTeX file generated by Academic Research Toolkit\n"
            f"% Contains {len(citations)} entries\n\n"
        )

        output_path.write_text(header + bibtex_content, encoding="utf-8")
        return str(output_path)

    def _format_entry(self, citation: Dict) -> Optional[str]:
        """Format a single citation as a BibTeX entry."""
        # Determine entry type
        citation_type = citation.get("citation_type", "unclassified")
        entry_type = self.TYPE_MAP.get(citation_type, "misc")

        # Generate citation key
        key = self._generate_key(citation)

        # Build fields based on entry type
        fields = self._build_fields(citation, entry_type)

        if not fields:
            return None

        # Format the entry
        lines = [f"@{entry_type}{{{key},"]
        for field_name, field_value in fields.items():
            escaped_value = self._escape_latex(field_value)
            lines.append(f"    {field_name} = {{{escaped_value}}},")
        lines.append("}")

        return "\n".join(lines)

    def _generate_key(self, citation: Dict) -> str:
        """Generate a unique citation key (author_year_title)."""
        # Get first author's last name
        authors = citation.get("authors", [])
        if authors:
            first_author = authors[0] if isinstance(authors, list) else str(authors)
            # Extract last name
            last_name = self._extract_last_name(first_author)
        else:
            last_name = "unknown"

        # Get year
        year = citation.get("year", "")
        if year:
            year = str(year).strip()
        else:
            year = "nodate"

        # Get title word
        title = citation.get("title", "")
        if title:
            # Get first significant word from title
            title_word = self._get_title_word(title)
        else:
            title_word = "untitled"

        # Create base key
        base_key = f"{last_name}_{year}_{title_word}".lower()
        base_key = self._sanitize_key(base_key)

        # Ensure uniqueness
        key = base_key
        counter = 1
        while key in self._used_keys:
            key = f"{base_key}_{counter}"
            counter += 1

        self._used_keys.add(key)
        return key

    def _extract_last_name(self, author: str) -> str:
        """Extract last name from author string."""
        author = author.strip()
        if not author:
            return "unknown"

        # Handle "Last, First" format
        if "," in author:
            return author.split(",")[0].strip()

        # Handle "First Last" format
        parts = author.split()
        if parts:
            return parts[-1].strip()

        return "unknown"

    def _get_title_word(self, title: str) -> str:
        """Get first significant word from title."""
        # Remove quotes if present
        title = title.strip().strip('"').strip("'")

        # Skip common articles
        skip_words = {"a", "an", "the", "on", "of", "in", "to", "for"}

        words = title.split()
        for word in words:
            # Clean the word
            clean_word = re.sub(r"[^\w]", "", word).lower()
            if clean_word and clean_word not in skip_words:
                return clean_word[:15]  # Limit length

        return "untitled"

    def _sanitize_key(self, key: str) -> str:
        """Sanitize citation key to be URL-safe and BibTeX-compatible."""
        # Remove accents
        key = unicodedata.normalize("NFKD", key)
        key = key.encode("ascii", "ignore").decode("ascii")
        # Replace non-alphanumeric with underscore
        key = re.sub(r"[^a-z0-9_]", "_", key)
        # Collapse multiple underscores
        key = re.sub(r"_+", "_", key)
        # Remove leading/trailing underscores
        key = key.strip("_")
        return key or "citation"

    def _build_fields(self, citation: Dict, entry_type: str) -> Dict[str, str]:
        """Build BibTeX fields for a citation."""
        fields = {}

        # Author field
        authors = citation.get("authors", [])
        if authors:
            if isinstance(authors, list):
                # BibTeX uses "and" to separate authors
                author_str = " and ".join(authors)
            else:
                author_str = str(authors)
            fields["author"] = author_str

        # Title field
        title = citation.get("title")
        if title:
            fields["title"] = title.strip().strip('"').strip("'")

        # Year field
        year = citation.get("year")
        if year:
            fields["year"] = str(year).strip()

        # Entry-type specific fields
        if entry_type == "book":
            if citation.get("publisher"):
                fields["publisher"] = citation["publisher"]
            if citation.get("location"):
                fields["address"] = citation["location"]

        elif entry_type == "article":
            if citation.get("source"):
                fields["journal"] = citation["source"]
            if citation.get("volume"):
                fields["volume"] = str(citation["volume"])
            if citation.get("issue"):
                fields["number"] = str(citation["issue"])
            if citation.get("pages"):
                fields["pages"] = citation["pages"]
            if citation.get("doi"):
                fields["doi"] = citation["doi"]

        # URL field for any type
        if citation.get("url"):
            fields["url"] = citation["url"]

        # Notes field
        if citation.get("notes"):
            fields["note"] = citation["notes"]

        return fields

    def _escape_latex(self, text: str) -> str:
        """Escape special LaTeX characters in text."""
        if not text:
            return ""

        result = str(text)

        # First, handle Unicode characters
        for char, latex in self.UNICODE_TO_LATEX.items():
            result = result.replace(char, latex)

        # Then escape special LaTeX characters
        for char, escape in self.LATEX_ESCAPES.items():
            result = result.replace(char, escape)

        return result

    def load_citations(self, citations_path: Path) -> List[Dict]:
        """
        Load citations from a JSON file.

        Args:
            citations_path: Path to JSON file containing citations.

        Returns:
            List of citation dictionaries.
        """
        citations_path = Path(citations_path)
        with citations_path.open("r", encoding="utf-8") as f:
            data = json.load(f)

        # Handle both list format and dict format with 'citations' key
        if isinstance(data, list):
            return data
        elif isinstance(data, dict) and "citations" in data:
            return data["citations"]
        else:
            return []
